language: python

sudo: false
python:
  - 2.7

matrix:
  include:
    - python: 2.7
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - set -e
  - pip install -U pip
  # Install prompt-toolkit from git until a release is made with
  # PROMPT_TOOLKIT_NO_CPR environment variable support.
  # Install jupyter_console from
  # https://github.com/jupyter/jupyter_console/pull/187 until it is included
  # in a release
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        pip install -U "pexpect>=3.3" pyflakes pytest epydoc rlipython requests jupyter flaky flake8;
    else
        pip install -U "pexpect>=3.3" pyflakes pytest rlipython requests jupyter flaky flake8;
        pip install -U git+https://github.com/prompt-toolkit/python-prompt-toolkit@2.0;
        pip install -U git+https://github.com/asmeurer/jupyter_console@display_completions;
    fi
  - pip list

script:
  - set -x
  - shopt -s extglob globstar
  # pyflakes all files except for known_imports/*, etc/*, and __init__.py,
  # which are all unused imports. We use flake8 so we can use noqa if
  # necessary.
  - flake8 --exclude known_imports,etc,__init__.py --select=F
  # Test for invalid escape sequences (will be syntax errors in a future
  # Python version)
  - python -We:invalid -m compileall -f -q lib/ etc/;
  - export DEBUG_TEST_PYFLYBY=1
  - pytest --doctest-modules lib tests
